### ISSUE TITLE
TypeError: ensure_ascii is an invalid keyword argument for print()

### ISSUE THREAD

**Issue by mathquis** [rhasspy/rhasspy-wake-raven#3]
Looks like there is something wrong here: 
https://github.com/rhasspy/rhasspy-wake-raven/blob/e662a5dd5ee55c24feec05bc74da48f8cd509633/rhasspywake_raven/__main__.py#L444

Reported here: https://community.rhasspy.org/t/raven-without-rhasspy/1778/4

Cheers

**Comment by synesthesiam** [comment]
Thanks! Fixed in 0fa941b1c273f7729e8ac0118aac26c158126ced
